name: Docs

on: [push, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: npm install -g @mermaid-js/mermaid-cli

    - name: Install Project
      run: make install

    - name: Generate Docs
      run: make docs

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html/
        force_orphan: true
